version: '1'
services:
  frontend:
    build: ./frontend
    ports:
      - '80:80'
    container_name: frontend-docker
    restart: always
    links:
      - backend

  backend:
    build: ./backend
    ports:
      - '5000:5000'
    container_name: backend-docker
    restart: always
